# Generated by Django 4.2.17 on 2025-03-07 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower_count', models.IntegerField(blank=True, null=True)),
                ('following_count', models.IntegerField(blank=True, null=True)),
                ('post_count', models.IntegerField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_scraped', models.IntegerField(default=0)),
                ('leads_generated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='targets.target')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['user', '-created_at'], name='targets_tar_user_id_7f7e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['username'], name='targets_tar_usernam_f28ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['is_active'], name='targets_tar_is_acti_41e1f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('user', 'username')},
        ),
    ]
