# Generated by Django 4.2.17 on 2025-03-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='license_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='total_listings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='total_properties_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='years_in_business',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='realtorpreference',
            name='platforms',
        ),
        migrations.AddField(
            model_name='realtorpreference',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='realtor_preferences', to='platforms.platform'),
        ),
    ]
