# Generated by Django 4.2.17 on 2025-05-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
        ('accounts', '0004_alter_realtor_social_media_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtorpreference',
            name='location_keywords',
        ),
        migrations.RemoveField(
            model_name='realtorpreference',
            name='target_pages',
        ),
        migrations.AddField(
            model_name='realtorpreference',
            name='default_frequency',
            field=models.CharField(choices=[('one-time', 'One-time request'), ('recurring', 'Recurring request')], default='one-time', max_length=20),
        ),
        migrations.AddField(
            model_name='realtorpreference',
            name='engagement_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='realtorpreference',
            name='repeat_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='realtorpreference',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='preferences', to='targets.target'),
        ),
    ]
