# Generated by Django 4.2.17 on 2025-05-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_alter_hashtag_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='platform',
        ),
    ]
