# Generated by Django 4.2.17 on 2025-05-28 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targets', '0001_initial'),
        ('hashtags', '0002_alter_hashtag_platform'),
        ('platforms', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_threshold', models.IntegerField(default=50)),
                ('default_frequency', models.CharField(choices=[('one-time', 'One-time request'), ('recurring', 'Recurring request')], default='one-time', max_length=20)),
                ('repeat_days', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashtags', models.ManyToManyField(to='hashtags.hashtag')),
                ('platforms', models.ManyToManyField(to='platforms.platform')),
                ('targets', models.ManyToManyField(to='targets.target')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Preference',
                'verbose_name_plural': 'Lead Preferences',
            },
        ),
    ]
