# Generated by Django 4.2.17 on 2025-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
        ('hashtags', '0002_alter_hashtag_platform'),
        ('platforms', '0001_initial'),
        ('leads', '0002_leadpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadpreference',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='hashtags.hashtag'),
        ),
        migrations.AlterField(
            model_name='leadpreference',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='platforms.platform'),
        ),
        migrations.AlterField(
            model_name='leadpreference',
            name='targets',
            field=models.ManyToManyField(blank=True, to='targets.target'),
        ),
    ]
