# Generated by Django 4.2.17 on 2025-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_add_canadian_cities'),
        ('leads', '0003_alter_leadpreference_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpreference',
            name='cities',
            field=models.ManyToManyField(blank=True, to='locations.city'),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='custom_locations',
            field=models.ManyToManyField(blank=True, to='locations.customlocation'),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='provinces',
            field=models.ManyToManyField(blank=True, to='locations.province'),
        ),
    ]
