# Generated by Django 4.2.17 on 2025-06-07 08:30
from django.db import migrations

def add_canadian_provinces(apps, schema_editor):
    Country = apps.get_model('locations', 'Country')
    Province = apps.get_model('locations', 'Province')
    
    canada = Country.objects.get(iso_code='CA')
    
    provinces = [
        ('Alberta', 'AB', 'PROVINCE'),
        ('British Columbia', 'BC', 'PROVINCE'),
        ('Manitoba', 'MB', 'PROVINCE'),
        ('New Brunswick', 'NB', 'PROVINCE'),
        ('Newfoundland and Labrador', 'NL', 'PROVINCE'),
        ('Nova Scotia', 'NS', 'PROVINCE'),
        ('Ontario', 'ON', 'PROVINCE'),
        ('Prince Edward Island', 'PE', 'PROVINCE'),
        ('Quebec', 'QC', 'PROVINCE'),
        ('Saskatchewan', 'SK', 'PROVINCE'),
        ('Northwest Territories', 'NT', 'TERRITORY'),
        ('Nunavut', 'NU', 'TERRITORY'),
        ('Yukon', 'YT', 'TERRITORY')
    ]
    
    for name, code, region_type in provinces:
        Province.objects.get_or_create(
            country=canada,
            name=name,
            code=code,
            region_type=region_type
        )

class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(add_canadian_provinces),
    ]