# Generated by Django 4.2.17 on 2025-06-11 14:13

from django.db import migrations


def add_canadian_cities(apps, schema_editor):
    Country = apps.get_model('locations', 'Country')
    Province = apps.get_model('locations', 'Province')
    City = apps.get_model('locations', 'City')

    # Get Canada and all provinces first
    canada = Country.objects.get(iso_code="CA")
    provinces = {
        "AB": Province.objects.get(country=canada, code="AB"),  # Alberta
        "BC": Province.objects.get(country=canada, code="BC"),  # British Columbia
        "MB": Province.objects.get(country=canada, code="MB"),  # Manitoba
        "NB": Province.objects.get(country=canada, code="NB"),  # New Brunswick
        "NL": Province.objects.get(country=canada, code="NL"),  # Newfoundland and Labrador
        "NS": Province.objects.get(country=canada, code="NS"),  # Nova Scotia
        "ON": Province.objects.get(country=canada, code="ON"),  # Ontario
        "PE": Province.objects.get(country=canada, code="PE"),  # Prince Edward Island
        "QC": Province.objects.get(country=canada, code="QC"),  # Quebec
        "SK": Province.objects.get(country=canada, code="SK"),  # Saskatchewan
        "NT": Province.objects.get(country=canada, code="NT"),  # Northwest Territories
        "NU": Province.objects.get(country=canada, code="NU"),  # Nunavut
        "YT": Province.objects.get(country=canada, code="YT"),  # Yukon
    }

    # Add all cities
    cities_data = [
        # Alberta
        ("Calgary", "AB"),
        ("Edmonton", "AB"),
        ("Red Deer", "AB"),
        ("Lethbridge", "AB"),
        # British Columbia
        ("Vancouver", "BC"),
        ("Victoria", "BC"),
        ("Surrey", "BC"),
        ("Kelowna", "BC"),
        # Manitoba
        ("Winnipeg", "MB"),
        ("Brandon", "MB"),
        ("Steinbach", "MB"),
        # New Brunswick
        ("Moncton", "NB"),
        ("Saint John", "NB"),
        ("Fredericton", "NB"),
        # Newfoundland and Labrador
        ("St. John's", "NL"),
        ("Corner Brook", "NL"),
        ("Gander", "NL"),
        # Nova Scotia
        ("Halifax", "NS"),
        ("Sydney", "NS"),
        ("Truro", "NS"),
        # Ontario
        ("Toronto", "ON"),
        ("Ottawa", "ON"),
        ("Mississauga", "ON"),
        ("Hamilton", "ON"),
        ("London", "ON"),
        # Prince Edward Island
        ("Charlottetown", "PE"),
        ("Summerside", "PE"),
        # Quebec
        ("Montreal", "QC"),
        ("Quebec City", "QC"),
        ("Laval", "QC"),
        ("Gatineau", "QC"),
        # Saskatchewan
        ("Saskatoon", "SK"),
        ("Regina", "SK"),
        ("Prince Albert", "SK"),
        # Northwest Territories
        ("Yellowknife", "NT"),
        ("Hay River", "NT"),
        ("Inuvik", "NT"),
        # Nunavut
        ("Iqaluit", "NU"),
        ("Rankin Inlet", "NU"),
        ("Arviat", "NU"),
        # Yukon
        ("Whitehorse", "YT"),
        ("Dawson City", "YT"),
        ("Watson Lake", "YT"),
    ]

    for city_name, province_code in cities_data:
        City.objects.get_or_create(
            name=city_name,
            province=provinces[province_code]
        )

def reverse_add_cities(apps, schema_editor):
    City = apps.get_model('locations', 'City')
    City.objects.filter(province__country__iso_code="CA").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_load_canadian_provinces'),  # Replace with your actual initial migration
    ]

    operations = [
        migrations.RunPython(add_canadian_cities, reverse_add_cities),
    ]


